### ISSUE TITLE
Nested arg destructuring breaks

### ISSUE THREAD

**Issue by saikyun** [fulcrologic/guardrails#10]
This breaks:
```clojure
(>defn add
  [[[k v] & wat]]
  [any? => number?]
  (+ 1 1))
;;=> Syntax error macroexpanding clojure.core/defn at (REPL:81:1).
;;=> ((k v) & wat :as arg_6480) - failed: Extra input at: [:fn-tail :arity-n :bodies :params] spec: :clojure.core.specs.alpha/param-list
;;=> ([(k v) & wat :as arg_6480]) - failed: Extra input at: [:fn-tail :arity-1 :params] spec: :clojure.core.specs.alpha/param-list
```

**Comment by awkay** [comment]
Looks like GR is converting the outer vector to a list. I have no time to work on this. My policy on issues is: if it isn't going to get worked on, I don't leave the noise in the issue tracker. If you care to try to make a PR for it, then feel free. Glad to look at a PR and merge it if it is sound. If nothing happens for a few weeks, I'll close this issue as "won't fix".

**Comment by saikyun** [comment]
Sorry for not replying earlier. I understand you position. Thanks for taking the time to reply. :)
