### ISSUE TITLE
Error: Unable to resolve spec: showing up for v.0.0.12

### ISSUE THREAD

**Issue by dvingo** [fulcrologic/guardrails#11]
I noticed when upgrading to guardrails 0.0.12 I am getting missing spec errors in the browser console for fulcro namespaces.

Version 0.0.11 does not have this issue.

Client only fulcro app demonstrating the bug:
https://github.com/dvingo/guardrails-0.0.12-bug

![guardrails_bug](https://user-images.githubusercontent.com/467827/84183454-f0623280-aa59-11ea-8ac7-686ce881aecf.png)

**Comment by awkay** [comment]
There was acgtually a bug in 0.0.11 that was emitting them when you said "no" in your config.  Check your config and make sure emit is set to true. I'm sure it was working "fine", but it was working because of a bug, not the other way around.

**Comment by dvingo** [comment]
ahhh, thank you! 

I blindly copied the config here:
https://github.com/fulcrologic/fulcro-template/blob/master/guardrails.edn

should have rtfm sooner...
