### ISSUE TITLE
Add Support for Running Guardrails on a Subset of Specs

### ISSUE THREAD

**Issue by dehli** [fulcrologic/guardrails#26]
It would be great if we could choose to run Guardrails on a subset of spec namespaces. My exact use-case is that I'm using an external library (https://github.com/wilkerlucio/pathom3) that's heavily using Guardrails. I'm also using it internally as a development tool. Ideally I'd be able to disable the specs from running in external libraries so that there's not as much of a performance impact.

If this is in scope of the library, I can try to take an initial swing at it. Thanks!

**Comment by awkay** [comment]
It is in scope, and I'd love to have it. Libraries like Pathom are great examples of where you'd like to exclude checks, since they are heavy. Let me know if you need any guidance.
