### ISSUE TITLE
Validates things not in the spec.

### ISSUE THREAD

**Issue by RokLenarcic** [fulcrologic/guardrails#9]
Sometimes this library will fail/throw on spec failure for map keys not defined in spec tested (but defined elsewhere. Here's a minimal working example (assuming you're using fulcro).

This code will not throw an error:
```
(com.fulcrologic.guardrails.core/run-check
  false
  {:log-level nil
   :vararg? false
   :throw true
   :fn-name "whatever"}
  (s/keys :req [:com.fulcrologic.fulcro.algorithms.form-state/config])
  {:com.fulcrologic.fulcro.algorithms.form-state/config
   {:com.fulcrologic.fulcro.algorithms.form-state/id [:component/id :user-info],
    :com.fulcrologic.fulcro.algorithms.form-state/fields #{},
    :com.fulcrologic.fulcro.algorithms.form-state/subforms {}}})
```

Now I'm going to add definition of a new spec:
```
(s/def ::test number?)
```

Now I'm going to add this key to the value tested, but not to the spec tested:
```
(com.fulcrologic.guardrails.core/run-check
  false
  {:log-level nil
   :vararg? false
   :throw true
   :fn-name "whatever"}
  (s/keys :req [:com.fulcrologic.fulcro.algorithms.form-state/config])
  {::test nil
   :com.fulcrologic.fulcro.algorithms.form-state/config
   {:com.fulcrologic.fulcro.algorithms.form-state/id [:component/id :user-info],
    :com.fulcrologic.fulcro.algorithms.form-state/fields #{},
    :com.fulcrologic.fulcro.algorithms.form-state/subforms {}}})
```

This produces an error because `::test` key doesn't fit its spec, but that's not expected behaviour for me because `::test` is not part of the spec being tested.

**Comment by RokLenarcic** [comment]
Seems like it's in spec itself that any namespaced map keys are automatically validated

**Comment by arichiardi** [comment]
I have been bitten by this, just wanted to share.the answers I am receiving here:

https://ask.clojure.org/index.php/10356/unexpected-spec-failure-on-namespaced-keys-not-included-req
